### ISSUE TITLE
6.x,数据权限更新操作一直报错

### ISSUE THREAD

**Issue by Gao-doc** [cool-team-official/cool-admin-midway#117]
unhandledRejection QueryFailedError: Field 'menuId' doesn't have a default value
    at Query.onResult (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\typeorm\src\driver\mysql\MysqlQueryRunner.ts:222:33)
    at Query.execute (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\connection.js:490:32)
    at PacketParser.onPacket (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\connection.js:95:12)
    at PacketParser.executeStart (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\connection.js:102:25)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  query: 'INSERT INTO `base_sys_role_menu`(`id`, `createTime`, `updateTime`, `roleId`, `menuId`) VALUES (DEFAULT, DEFAULT, DEFAULT, ?, DEFAULT)',
  parameters: [ 11 ],
  driverError: Error: Field 'menuId' doesn't have a default value
      at Packet.asError (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\connection.js:490:32)
      at PacketParser.onPacket (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\connection.js:95:12)
      at PacketParser.executeStart (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\Lenovo\桌面\cool6\cool-admin-midway\node_modules\mysql2\lib\connection.js:102:25)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {
    code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlState: 'HY000',
    sqlMessage: "Field 'menuId' doesn't have a default value",
    sql: 'INSERT INTO `base_sys_role_menu`(`id`, `createTime`, `updateTime`, `roleId`, `menuId`) VALUES (DEFAULT, DEFAULT, DEFAULT, 11, DEFAULT)'
  },
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'menuId' doesn't have a default value",
  sql: 'INSERT INTO `base_sys_role_menu`(`id`, `createTime`, `updateTime`, `roleId`, `menuId`) VALUES (DEFAULT, DEFAULT, DEFAULT, 11, DEFAULT)'
}

**Comment by cool-team-official** [comment]
已修复
