### ISSUE TITLE
npm更新到最新版本midway脚手架 启动报错

### ISSUE THREAD

**Issue by KaneOne** [cool-team-official/cool-admin-midway#12]
无法创建type文件

> cool-admin@3.0.0 dev C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway
> cross-env ets && cross-env NODE_ENV=local TS_NODE_TYPE_CHECK=false TS_NODE_TRANSPILE_ONLY=true midway-bin dev --ts --port=8001 --sticky

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:139:9)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\locate-path\index.js:20:28)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\find-up\index.js:34:27)
    at Object.findLernaRoot (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\utils.js:37:22)
    at EggAppWorkerLoader.getEggPaths (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:53:42)
    at new EggLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg-core\lib\loader\egg_loader.js:72:26)
    at new AppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg\lib\loader\app_worker_loader.js:9:1)
    at new EggAppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:38:13)
    at getLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\eggInfo.js:94:10)
Error: Command failed: node C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\eggInfo
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:139:9)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\locate-path\index.js:20:28)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\find-up\index.js:34:27)
    at Object.findLernaRoot (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\utils.js:37:22)
    at EggAppWorkerLoader.getEggPaths (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:53:42)
    at new EggLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg-core\lib\loader\egg_loader.js:72:26)
    at new AppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg\lib\loader\app_worker_loader.js:9:1)
    at new EggAppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:38:13)
    at getLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\eggInfo.js:94:10)

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.getEggInfo (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\bin.js:50:21)
    at getDefaultWatchDirs (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:57:46)
    at TsHelper.configure (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:247:28)
    at new TsHelper (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:106:14)
    at Object.createTsHelperInstance (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:365:12)
    at execute (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\bin.js:64:25)
    at Object.<anonymous> (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\bin.js:34:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 54 79 70 65 45 72 72 6f 72 20 5b 45 52 52 5f 49 4e 56 41 4c 49 44 5f 41 52 47 5f 54 59 50 45 5d 3a 20 
54 68 65 20 22 70 61 74 68 22 20 61 72 67 75 6d ... 1232 more bytes>
  ],
  pid: 17660,
  stdout: <Buffer >,
  stderr: <Buffer 54 79 70 65 45 72 72 6f 72 20 5b 45 52 52 5f 49 4e 56 41 4c 49 44 5f 41 52 47 5f 54 59 50 45 5d 
3a 20 54 68 65 20 22 70 61 74 68 22 20 61 72 67 75 6d ... 1232 more bytes>
}
[egg-ts-helper] create typings\app\index.d.ts (2ms)
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\typings\config\plugin.d.ts'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\bin.js:68:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\kane\\Desktop\\Dev\\cool-admin\\cool-admin-midway\\typings\\config\\plugin.d.ts'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cool-admin@3.0.0 dev: `cross-env ets && cross-env NODE_ENV=local TS_NODE_TYPE_CHECK=false TS_NODE_TRANSPILE_ONLY=true midway-bin dev --ts --port=8001 --sticky`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cool-admin@3.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kane\AppData\Roaming\npm-cache\_logs\2021-03-31T02_29_05_679Z-debug.log
PS C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway> npm run dev

> cool-admin@3.0.0 dev C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway
> cross-env ets && cross-env NODE_ENV=local TS_NODE_TYPE_CHECK=false TS_NODE_TRANSPILE_ONLY=true midway-bin dev --ts --port=8001 --sticky

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:139:9)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\locate-path\index.js:20:28)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\find-up\index.js:34:27)
    at Object.findLernaRoot (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\utils.js:37:22)
    at EggAppWorkerLoader.getEggPaths (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:53:42)
    at new EggLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg-core\lib\loader\egg_loader.js:72:26)
    at new AppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg\lib\loader\app_worker_loader.js:9:1)
    at new EggAppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:38:13)
    at getLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\eggInfo.js:94:10)
Error: Command failed: node C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\eggInfo
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:139:9)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\locate-path\index.js:20:28)
    at Function.module.exports.sync (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\find-up\index.js:34:27)
    at Object.findLernaRoot (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\utils.js:37:22)
    at EggAppWorkerLoader.getEggPaths (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:53:42)
    at new EggLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg-core\lib\loader\egg_loader.js:72:26)
    at new AppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\egg\lib\loader\app_worker_loader.js:9:1)
    at new EggAppWorkerLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\web\dist\base.js:38:13)
    at getLoader (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\eggInfo.js:94:10)

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.getEggInfo (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\bin.js:50:21)
    at getDefaultWatchDirs (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:57:46)
    at TsHelper.configure (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:247:28)
    at new TsHelper (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:106:14)
    at Object.createTsHelperInstance (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\index.js:365:12)
    at execute (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\bin.js:64:25)
    at Object.<anonymous> (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\node_modules\egg-ts-helper\dist\bin.js:34:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 54 79 70 65 45 72 72 6f 72 20 5b 45 52 52 5f 49 4e 56 41 4c 49 44 5f 41 52 47 5f 54 59 50 45 5d 3a 20 
54 68 65 20 22 70 61 74 68 22 20 61 72 67 75 6d ... 1232 more bytes>
  ],
  pid: 7460,
  stdout: <Buffer >,
  stderr: <Buffer 54 79 70 65 45 72 72 6f 72 20 5b 45 52 52 5f 49 4e 56 41 4c 49 44 5f 41 52 47 5f 54 59 50 45 5d 
3a 20 54 68 65 20 22 70 61 74 68 22 20 61 72 67 75 6d ... 1232 more bytes>
}
[egg-ts-helper] create typings\app\index.d.ts (3ms)
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\typings\config\plugin.d.ts'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\Users\kane\Desktop\Dev\cool-admin\cool-admin-midway\node_modules\@midwayjs\egg-ts-helper\bin.js:68:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\kane\\Desktop\\Dev\\cool-admin\\cool-admin-midway\\typings\\config\\plugin.d.ts'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cool-admin@3.0.0 dev: `cross-env ets && cross-env NODE_ENV=local TS_NODE_TYPE_CHECK=false TS_NODE_TRANSPILE_ONLY=true midway-bin dev --ts --port=8001 --sticky`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cool-admin@3.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kane\AppData\Roaming\npm-cache\_logs\2021-03-31T02_30_33_281Z-debug.log

**Comment by cool-team-official** [comment]
拉取最新代码
