### ISSUE TITLE
报错太多了 完全不能用啊 utf8mb4_0900_ai_ci 数据库一定要高版本么？查询能否mysql redis联动增删改查 而且 dict_info初始化编码会出错 ENGINE = InnoDB AUTO_INCREMENT = 31 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic; 

### ISSUE THREAD

**Issue by ghost** [cool-team-official/cool-admin-midway#141]
at Query.execute (D:\WorckCode-WEB\server\node_modules\mysql2\lib\commands\command.js:36:14)
    at PoolConnection.handlePacket (D:\WorckCode-WEB\server\node_modules\mysql2\lib\connection.js:478:34)
    at PacketParser.onPacket (D:\WorckCode-WEB\server\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (D:\WorckCode-WEB\server\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\WorckCode-WEB\server\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {  
  query: 'UPDATE `base_sys_user` SET `passwordV` = ?, `headImg` = 
?, `updateTime` = CURRENT_TIMESTAMP WHERE `id` IN (?)',
  parameters: [ 8, [], 1 ],
  driverError: Error: You have an error in your SQL syntax; check 
the manual that corresponds to your MySQL server version for the right syntax to use near ' `updateTime` = CURRENT_TIMESTAMP WHERE `id` IN (1)' at line 1
      at Packet.asError (D:\WorckCode-WEB\server\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (D:\WorckCode-WEB\server\node_modules\mysql2\lib\commands\command.js:29:26)
      at PoolConnection.handlePacket (D:\WorckCode-WEB\server\node_modules\mysql2\lib\connection.js:478:34)
      at PacketParser.onPacket (D:\WorckCode-WEB\server\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (D:\WorckCode-WEB\server\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (D:\WorckCode-WEB\server\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9) {    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right 
syntax to use near ' `updateTime` = CURRENT_TIMESTAMP WHERE `id` IN (1)' at line 1",
    sql: 'UPDATE `base_sys_user` SET `passwordV` = 8, `headImg` = 
, `updateTime` = CURRENT_TIMESTAMP WHERE `id` IN (1)'
  },
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `updateTime` = CURRENT_TIMESTAMP WHERE `id` IN 
(1)' at line 1",
  sql: 'UPDATE `base_sys_user` SET `passwordV` = 8, `headImg` = , 
`updateTime` = CURRENT_TIMESTAMP WHERE `id` IN (1)'
}
2023-10-05 22:16:17,365 ERROR 6020 TypeError: Cannot read properties of undefined (reading 'getRepeatableJobs')
    at TaskInfoQueue.getRepeatableJobs (D:\WorckCode-WEB\server\node_modules\@cool-midway\task\base.js:51:31)
    at TaskInfoService.exist (D:\WorckCode-WEB\server\src\modules\task\service\info.ts:112:45)
    at TaskInfoService.delete (D:\WorckCode-WEB\server\src\modules\task\service\info.ts:189:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TaskInfoController.delete (D:\WorckCode-WEB\server\node_modules\@cool-midway\core\controller\base.js:95:24)
    at async D:\WorckCode-WEB\server\node_modules\@midwayjs\core\dist\common\webGenerator.js:43:26
    at async D:\WorckCode-WEB\server\src\modules\task\middleware\task.ts:28:7
    at async D:\WorckCode-WEB\server\node_modules\@midwayjs\info\dist\middleware\info.middleware.js:35:24
    at async D:\WorckCode-WEB\server\src\modules\user\middleware\app.ts:58:7
2023-10-05 22:16:21,298 ERROR 6020 TypeError: Cannot read properties of undefined (reading 'getRepeatableJobs')
    at TaskInfoQueue.getRepeatableJobs (D:\WorckCode-WEB\server\node_modules\@cool-midway\task\base.js:51:31)
    at TaskInfoService.exist (D:\WorckCode-WEB\server\src\modules\task\service\info.ts:112:45)
    at TaskInfoService.delete (D:\WorckCode-WEB\server\src\modules\task\service\info.ts:189:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TaskInfoController.delete (D:\WorckCode-WEB\server\node_modules\@cool-midway\core\controller\base.js:95:24)
    at async D:\WorckCode-WEB\server\node_modules\@midwayjs\core\dist\common\webGenerator.js:43:26
    at async D:\WorckCode-WEB\server\src\modules\task\middleware\task.ts:28:7
    at async D:\WorckCode-WEB\server\node_modules\@midwayjs\info\dist\middleware\info.middleware.js:35:24
    at async D:\WorckCode-WEB\server\src\modules\user\middleware\app.ts:58:7
2023-10-05 22:17:24,459 ERROR 6020 TypeError: Cannot read properties of undefined (reading 'getRepeatableJobs')
    at TaskInfoQueue.getRepeatableJobs (D:\WorckCode-WEB\server\node_modules\@cool-midway\task\base.js:51:31)
    at TaskInfoService.exist (D:\WorckCode-WEB\server\src\modules\task\service\info.ts:112:45)
    at TaskInfoService.delete (D:\WorckCode-WEB\server\src\modules\task\service\info.ts:189:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TaskInfoController.delete (D:\WorckCode-WEB\server\node_modules\@cool-midway\core\controller\base.js:95:24)
    at async D:\WorckCode-WEB\server\node_modules\@midwayjs\core\dist\common\webGenerator.js:43:26
    at async D:\WorckCode-WEB\server\src\modules\task\middleware\task.ts:28:7
    at async D:\WorckCode-WEB\server\node_modules\@midwayjs\info\dist\middleware\info.middleware.js:35:24
    at async D:\WorckCode-WEB\server\src\modules\user\middleware\app.ts:58:7

**Comment by cool-team-official** [comment]
拉最新代码
