### ISSUE TITLE
ERROR 6908 NotFoundError: /admin/base/sys/department/list Not Found

### ISSUE THREAD

**Issue by shoppinglink** [cool-team-official/cool-admin-midway#145]
刚拉取的最新版本，系统管理-权限管理-用户列表，组织架构一直在加载中。接口返回{"code":404,"message":"/admin/base/sys/department/list Not Found"}
后台报错：
```
ERROR 6908 NotFoundError: /admin/base/sys/department/list Not Found
    at notFound (G:\admin-midway\node_modules\@midwayjs\koa\dist\framework.js:94:23)
    at async G:\admin-midway\node_modules\@midwayjs\info\dist\middleware\info.middleware.js:35:24
    at async G:\admin-midway\src\modules\user\middleware\app.ts:58:7
    at async G:\admin-midway\src\modules\base\middleware\log.ts:23:7
    at async G:\admin-midway\src\modules\base\middleware\authority.ts:84:15
    at async G:\admin-midway\node_modules\@midwayjs\i18n\dist\middleware.js:150:17
    at async bodyParser (G:\admin-midway\node_modules\koa-bodyparser\index.js:78:5)
    at async session (G:\admin-midway\node_modules\@midwayjs\session\dist\middleware\session.js:137:17)
    at async G:\admin-midway\node_modules\koa-static-cache\index.js:41:56
    at async G:\admin-midway\node_modules\@midwayjs\core\dist\baseFramework.js:277:40 {
  code: '404',
  cause: undefined,
  status: 404
}
```

**Comment by cool-team-official** [comment]
删除前端的 build/cool/dist  重试， 或者清除缓存

**Comment by shoppinglink** [comment]
我试过清除缓存不能解决，这个方法可以：删除前端的 build/cool/dist（原因是post方法，结果用get请求的方式）。十分感谢！！
