### ISSUE TITLE
 [cool:core] midwayjs cool core init base database err please manual import

### ISSUE THREAD

**Issue by Xingsir1991** [cool-team-official/cool-admin-midway#15]
2021-04-12 10:07:44,413 ERROR 22976  [cool:core] midwayjs cool core init base database err please manual import 
2021-04-12 10:07:44,413 ERROR 22976 Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
    at Query.Sequence._packetToError (D:\work\cool-admin-midway\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\work\cool-admin-midway\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\work\cool-admin-midway\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\work\cool-admin-midway\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\work\cool-admin-midway\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\work\cool-admin-midway\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\work\cool-admin-midway\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\work\cool-admin-midway\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    --------------------
    at Protocol._enqueue (D:\work\cool-admin-midway\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\work\cool-admin-midway\node_modules\mysql\lib\Connection.js:198:25)
    at D:\work\cool-admin-midway\node_modules\mysql-import\mysql-import.js:466:23
    at new Promise (<anonymous>)
    at queryParser.executeQuery (D:\work\cool-admin-midway\node_modules\mysql-import\mysql-import.js:465:10)
    at queryParser._write (D:\work\cool-admin-midway\node_modules\mysql-import\mysql-import.js:452:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by cool-team-official** [comment]
mysql数据库版本>=5.7
