### ISSUE TITLE
dev启动报错

### ISSUE THREAD

**Issue by wmn1525** [cool-team-official/cool-admin-midway#170]
`➜  Local:    http://127.0.0.1:8001/ 
Error: ENOENT: no such file or directory, open 'E:\Work\Project\cool-admin-midway\dist\modules\base\config.ts'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at BaseAppEvent.onServerReady (E:\Work\Project\cool-admin-midway\src\modules\base\event\app.ts:32:25)
    at CoolEventManager.<anonymous> (E:\Work\Project\cool-admin-midway\node_modules\@cool-midway\core\event\index.js:34:50)
➜  Network:  http://192.168.50.210:8001/ `

**Comment by ryuusennka** [comment]
我也遇到了同样的错误,我今天才开始学习这个框架,刚clone下来的项目,启动 dev 就报错了,是报的同样的错误;

**可能需要改动两个文件,但是我不确定这样做是否正确,就是把**
```
src\modules\base\event\app.ts
src\modules\user\event\app.ts
```
的`config.ts`改为`config.js`
![image](https://github.com/cool-team-official/cool-admin-midway/assets/13093163/5f03e898-e4e0-4a11-aac8-e87aea28a052)

**Comment by cool-team-official** [comment]
拉 最新的代码
