### ISSUE TITLE
[ Midway ] start error: Unexpected token =

### ISSUE THREAD

**Issue by baobz** [cool-team-official/cool-admin-midway#7]
当我从github上拉去项目, 使用cnpm i安装依赖, 但是当我启动项目npm run dev时抛出一个错误
`
[ Midway ] start error: Unexpected token =
F:\xxxx\cool-admin-midway\node_modules\_@4a_cid@0.1.0@@4a\cid\index.js:4
    base = 15 // 基础长度
         ^

SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
`
不知道是我哪一步出现了错误, 请帮忙指点一下, 谢谢!

**Comment by cool-team-official** [comment]
应该是你的node版本过低，midway要求>=12.x , 你试试下载node 14.x 最新的版本 ，然后删除node_modules，建议使用cnpm 重新安装依赖。
