### ISSUE TITLE
modules is not iterable

### ISSUE THREAD

**Issue by sponing** [cool-team-official/cool-admin-midway#77]
[ Midway ] start error: modules is not iterable
TypeError: modules is not iterable
    at CoolModuleImport.init (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@cool-midway/core/module/import.js:33:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ObjectCreator.doInitAsync (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@midwayjs/core/dist/definitions/objectCreator.js:111:17)
    at ManagedResolverFactory.createAsync (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:252:9)
    at CoolConfiguration.onReady (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@cool-midway/core/configuration.js:30:9)
    at MidwayLifeCycleService.runContainerLifeCycle (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@midwayjs/core/dist/service/lifeCycleService.js:88:36)
    at MidwayLifeCycleService.init (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@midwayjs/core/dist/service/lifeCycleService.js:56:9)
    at ObjectCreator.doInitAsync (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@midwayjs/core/dist/definitions/objectCreator.js:111:17)
    at ManagedResolverFactory.createAsync (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@midwayjs/core/dist/context/managedResolverFactory.js:252:9)
    at initializeGlobalApplicationContext (/Users/user/Documents/personal/git/concludeOrStLearn/midway/midway-project/node_modules/@midwayjs/core/dist/setup.js:31:5)

**Comment by cool-team-official** [comment]
你不能单独 使用@cool-midway/core  得遵循 cool-admin的项目目录结构
